### ISSUE TITLE
App Closes and Cannot Connect to Watch

### ISSUE THREAD

**Issue by munsterlander** [guikeller/cordova-samsung-accessory-plugin#1]
So after implementing the suggested timer, I was able to get the provider app to connect to the watch once but not consistently after that.  When you run the HelloAccessory widget app from the sample on the device and tap connect, Tizen reports it has connected to the remotePeer and the app on the phone then crashes without an error log.  When it did connect from the phone side that one instance, I received this error in the console.

```
Error in Success callbackId: CordovaSamsungAccessoryPlugin976966679 : TypeError: callback.success.apply is not a function
cordova.js:307 TypeError: callback.success.apply is not a function
    at Object.callbackFromNative (cordova.js:288)
    at <anonymous>:1:9
cordova.js:288 Uncaught TypeError: callback.success.apply is not a function
    at Object.callbackFromNative (cordova.js:288)
    at <anonymous>:1:9
```

Provider (Samsung Galaxy S8, non root, Android running Cordova) Code:

```
function goGalaxy(val){
  console.log ("Called goGalaxy");
  /* GalaxyGear.onConnect(function(e) {
      console.log("Connection Successfully Established - handle: " + e.handle);
      
      GalaxyGear.onDataReceived(e.handle, function(e) {
        console.log("Data received - handle: " + e.handle + " data: "+ e.data);
      });
      
    });
    */
    var msg = "Initiated";
    if(val = typeof val !== 'undefined'){
      msg = "The item "+val+" that was identified as a target has been detected.";
    }
    // Receiving messages from Watch - callbacks
    var receiveMessageSuccess = function(message){
        var value = JSON.stringify(message);
        console.log("Received message from Watch : "+value);
    };
    var receiveMessageFailure = function() {
        console.log("Could not receive message from Watch");
    };

    // Sending Messages to Watch - callbacks
    var sendMessageSuccess = function() {
        console.log("Message sent successfully!");
    };
    var sendMessageFailure = function(){
        console.log("Could not send message to Watch.");
    };

    var findPeerSuccess = function(msg) {
      console.log("Peer found success");
        // Sends a message to the Watch
        SamsungAccessoryPlugin.sendMessage(msg, sendMessageSuccess, sendMessageFailure);    
    };
    var findPeerFailure = function() {
        console.log("Could not find any peers.");
    };
    
    // Initialised a Session successfully
    var initWatchSuccess = function() {
      console.log("Init Success");
        // Wait for 5secs, SAP 'should have' initialised after that..
        window.setTimeout( () => {
            console.log("Timer called");
            // Tries to find the peer / watch
            SamsungAccessoryPlugin.findPeer(findPeerSuccess, findPeerFailure); // See GITHUB
	    // Register to receive messages
            console.log("registering listener");
            SamsungAccessoryPlugin.registerMessageListener(receiveMessageSuccess, receiveMessageFailure); // See GITHUB
        }, 5000);
    };
    var initWatchFailure = function() {
        console.log("Could not connect to Watch.");
    };
    
    // Starts things up
    SamsungAccessoryPlugin.init(initWatchSuccess, initWatchFailure);

}
```

Device (Samsung Gear Frontier 3) Code:

```
var SAAgent = null;
var SASocket = null;
var CHANNELID = 104;
var ProviderAppName = "CordovaSamsungPluginApp";
//var arrTargets;
//var initialRun;

function createHTML(log_string)
{
	var content = document.getElementById("toast-content");
	content.textContent = log_string;
	tau.openPopup("#toast");
}

function onerrorPeer(err) {
	console.log("Hello err Peer [" + err + "]");
}

function onerrorAgent(err) {
	console.log("Hello err Agent [" + err + "]");
}

var agentCallback = {
	onconnect : function(socket) {
		SASocket = socket;
		//if(initialRun){
			createHTML("FeedLogger Connection established with RemotePeer");
		//	initialRun=false;
		//	arrTargets = new Array();
		//}
		SASocket.setSocketStatusListener(function(reason){
			console.log("FeedLogger Service connection lost, Reason : [" + reason + "]");
			disconnect();
		});
		SASocket.setDataReceiveListener(onreceive);
	},
	onerror : onerrorAgent
};

var peerAgentFindCallback = {
	onpeeragentfound : function(peerAgent) {
		try {
			if (peerAgent.appName === ProviderAppName) {
				SAAgent.setServiceConnectionListener(agentCallback);
				SAAgent.requestServiceConnection(peerAgent);
			} else {
				console.log("Hello Not expected app!! : " + peerAgent.appName);
			}
		} catch(err) {
			console.log("Hello exception with peer [" + err.name + "] msg[" + err.message + "]");
		}
	},
	onerror : onerrorPeer
};

function onsuccess(agents) {
	try {
		if (agents.length > 0) {
			SAAgent = agents[0];
			SAAgent.setPeerAgentFindListener(peerAgentFindCallback);
			SAAgent.findPeerAgents();
		} else {
			console.log("Hello Not found SAAgent!!");
		}
	} catch(err) {
		console.log("Hello exception onSuccess [" + err.name + "] msg[" + err.message + "]");
	}
}

function connect() {
	if (SASocket) {
		createHTML('FeedLogger Already connected!');
        return false;
    }
	try {
		webapis.sa.requestSAAgent(onsuccess, function (err) {
			console.log("Hello Connect err [" + err.name + "] msg[" + err.message + "]");
		});
	} catch(err) {
		console.log("Hello Connect exception [" + err.name + "] msg[" + err.message + "]");
	}
}

function disconnect() {
	try {
		if (SASocket !== null) {			
			/*if (pressed = typeof pressed !== 'undefined'){
				SASocket.close();
				SASocket = null;
				createHTML("closeConnection");
			} else {*/
				SASocket.close();
				SASocket = null;
				createHTML("closeConnection");
				//connect();
			//}
			
		}
	} catch(err) {
		console.log("Hello disconnect exception [" + err.name + "] msg[" + err.message + "]");
	}
}

function onreceive(channelId, data) {
	console.log(JSON.stringify(data));
	//if(arrTargets.indexOf(data) < 0 && !initialRun){
	//	arrTargets.push(data);
		createHTML(data.message);
		navigator.vibrate(1000);
	//}
}

function fetch() {
	try {
		SASocket.sendData(CHANNELID, "FeedLogger Handshake!");
	} catch(err) {
		console.log("Hello fetch exception [" + err.name + "] msg[" + err.message + "]");
	}
}

window.onload = function () {
    // add eventListener for tizenhwkey
	//initialRun = true;
    document.addEventListener('tizenhwkey', function(e) {
        if(e.keyName === "back"){
            tizen.application.getCurrentApplication().exit();
        }
    });
};

(function(tau) {
	var toastPopup = document.getElementById('toast');
	toastPopup.addEventListener('popupshow', function(ev){
		setTimeout(function(){tau.closePopup();}, 3000);
	}, false);
})(window.tau);
```

Relevant Logcat output:

```
10-10 08:12:14.814  3688  5547 W System.err: java.lang.NullPointerException: Attempt to read from field 'java.lang.String aE.q.mPackageName' on a null object reference
10-10 08:12:14.814  3688  5547 W System.err: 	at aE.f.a(Unknown Source:134)
10-10 08:12:14.814  3688  5547 W System.err: 	at aE.M.a(Unknown Source:350)
10-10 08:12:14.814  3688  5547 W System.err: 	at aE.M.a(Unknown Source:2)
10-10 08:12:14.814  3688  5547 W System.err: 	at com.sec.android.sdhms.common.o.r(Unknown Source:22)
10-10 08:12:14.814  3688  5547 W System.err: 	at k.d.noteResumeComponent(Unknown Source:33)
10-10 08:12:14.814  3688  5547 W System.err: 	at com.samsung.android.app.usage.IUsageStatsWatcher$Stub.onTransact(IUsageStatsWatcher.java:67)
10-10 08:12:14.814  3688  5547 W System.err: 	at android.os.Binder.execTransact(Binder.java:739)
10-10 08:12:14.817  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.818  1518  5462 D SamsungPhoneWindowManager: adjustSystemUiVisibilityLw: vis=0x8018
10-10 08:12:14.818  1518  5462 D InputManager-JNI: setSystemUiVisibility dexmode: false changed: true displayid: 0 visibility: 0x8018 DD: 0x8018 OD: 0x0
10-10 08:12:14.819  4106  4106 D ViewRootImpl@c67adda[LauncherActivity]: Relayout returned: old=[0,0][1080,2220] new=[0,0][1080,2220] result=0x1 surface={valid=false 0} changed=false
10-10 08:12:14.819  4106  4106 D ViewRootImpl@c67adda[LauncherActivity]: setWindowStopped(false) old=true
10-10 08:12:14.820  4106  4106 D TrayManager: TrayManagerImp:resetMoving() mMoved: false
10-10 08:12:14.820  4106  4106 D TrayManager: TrayManagerImp:setTrayTranslationY() current: Underground dest: Overground
10-10 08:12:14.820  4106  4106 D TrayManager: send changed offset. sender: Overground current: Underground dest: Overground
10-10 08:12:14.821  4106  4106 D HomeContainer: setAlpha : 0.0 visibility : 8
10-10 08:12:14.821  4106  4106 D PageOverlayMover: updateActivityLifecycleState : 1
10-10 08:12:14.822  4106  4106 D ViewRootImpl@c67adda[LauncherActivity]: setWindowStopped(false) old=false
10-10 08:12:14.823  4106  4106 V Launcher: Launcher.onResume()
10-10 08:12:14.823  4106  4106 D Launcher: !@Boot_DEBUG: Launcher.onResume()
10-10 08:12:14.823  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.828  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.831  4106  4106 D LauncherResumeCallbacksManager: mRunResumeCallbackInSchedule needToRun!
10-10 08:12:14.833  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.834  4106  4106 D ExternalMethodQueue: Getting and clearing EXTERNAL_METHOD_LIST: null
10-10 08:12:14.835  4106  4106 D ExternalRequestQueue: Getting and clearing EXTERNAL_REQUEST_LIST: 0
10-10 08:12:14.839  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.839   651 22896 D msm8974_platform: platform_set_channel_map mixer_ctl_name:Playback Channel Map13
10-10 08:12:14.840   651 22896 D msm8974_platform: platform_set_channel_map: set mapping(1 2 0 0 0 0 0 0) for channel:2
10-10 08:12:14.840   651 22896 D audio_hw_primary: start_output_stream: exit
10-10 08:12:14.840  4106  4106 D AppsDataRepository: updateAppIcons start : 
10-10 08:12:14.841  4106  4106 D AppsDataRepository: updateItemsAndContents items size: 20, screenType: 0
10-10 08:12:14.841  4106  4106 D AppsDataRepository: no change items 20
10-10 08:12:14.841  4106  4106 D AppsDataRepository: updateItemsAndContents items size: 0, screenType: 1
10-10 08:12:14.841  4106  4106 D AppsDataRepository: no change items 0
10-10 08:12:14.841  4106  4106 D AppsPresenter: AppsEvent update [15]
10-10 08:12:14.842  4106  4106 D AppsPresenter: AppsEvent update [5]
10-10 08:12:14.842  4106  4106 D AppsDataRepository: notifyUpdate end : 
10-10 08:12:14.843  4106  4106 D StageManager: onResume. topStage: com.android.launcher3.infra.stage.AppsStage@84d7bc6 alpha: 1.0 visibility: 0
10-10 08:12:14.845  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.847  1518  2008 W InputDispatcher: channel '75d4f9f com.cfuze.feedlogger/com.cfuze.feedlogger.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=557
10-10 08:12:14.847  1518  2008 E InputDispatcher: channel '75d4f9f com.cfuze.feedlogger/com.cfuze.feedlogger.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-10 08:12:14.849  4106  4106 D PageOverlayMover: updateActivityLifecycleState : 2
10-10 08:12:14.849  4106  4106 D HotwordClientUtils: setHotWordDetection : call requestHotWordDetection true
10-10 08:12:14.849  4106  4106 D Launcher.HomeStage: onResume HomeContainer current alpha = 0.0
10-10 08:12:14.849  4106  4106 D WallpaperScrollUtils: setupWallpaperScroller
10-10 08:12:14.849  4106  4106 D WallpaperScrollUtils: WallpaperTiltSettingEnabled : false
10-10 08:12:14.849  4106  4106 D Notification.Badge: setNotificationsChangedListener
10-10 08:12:14.850  1518  5410 D MediaFocusControl: AudioFocus audio focus client died
10-10 08:12:14.850  1518  5410 I MediaFocusControl: AudioFocus  removeFocusStackEntryOnDeath(): removing entry for android.os.BinderProxy@c84d477
10-10 08:12:14.850  1518  1569 W libprocessgroup: kill(-31288, 9) failed: No such process
10-10 08:12:14.851  4981  5204 I SAFrameworkService: Package [com.cfuze.feedlogger] has died!!
```

I am continuing to work on this and will keep this thread updated.

**Comment by guy-keller** [comment]
Hi @munsterlander 

I believe that you're very close to getting it all going.

That: _TypeError: callback.success.apply is not a function_ implies that something is missing a callback
https://stackoverflow.com/questions/41996345/typeerror-callback-apply-is-not-a-function
This indicates to me that one of the method calls is somehow wrong.

Next step was to look at the method signatures of the plugin:
```
module.exports = {
    init: function(successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "CordovaSamsungAccessoryPlugin", "init", []);
    },
    shutdown: function(onNewMessageCallback, errorCallback) {
        cordova.exec(onNewMessageCallback, errorCallback, "CordovaSamsungAccessoryPlugin", "shutdown", []);
    },
    findPeer: function(successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "CordovaSamsungAccessoryPlugin", "findPeer", []);
    },
    sendMessage: function(successCallback, errorCallback, message) {
        cordova.exec(successCallback, errorCallback, "CordovaSamsungAccessoryPlugin", "sendMessage", [message]);
    },
    registerMessageListener: function(successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "CordovaSamsungAccessoryPlugin", "registerMessageListener", []);
    }
};
```

Then one by one:
```
SamsungAccessoryPlugin.init(initWatchSuccess, initWatchFailure);
init: function(successCallback, errorCallback) // match

SamsungAccessoryPlugin.findPeer(findPeerSuccess, findPeerFailure);
findPeer: function(successCallback, errorCallback) // match

SamsungAccessoryPlugin.registerMessageListener(receiveMessageSuccess, receiveMessageFailure);
registerMessageListener: function(successCallback, errorCallback) // match

SamsungAccessoryPlugin.sendMessage(msg, sendMessageSuccess, sendMessageFailure);
sendMessage: function(successCallback, errorCallback, message) // MISMATCH, ERROR
```

Please try this way here:
```
// success callback, error callback, message/value
SamsungAccessoryPlugin.sendMessage(sendMessageSuccess, sendMessageFailure, msg);
```

Thanks for reporting the error and providing info!
Ultimately my sample usage has a 'little bug', my bad.

Can you please let me know how you go? Cheers!

**Comment by munsterlander** [comment]
@guikeller Thank you!  That has fixed that error but unfortunately not the problem.  It connects and both show they are connected.  When a message is being sent from the phone to the watch, the app crashes on the phone.  This is the logcat:

```
10-10 18:20:08.160  1518  1591 D WindowManager: reportFocusChangedSerialized, focused=false, inTouchMode=true, win=Window{d66d79b u0 Application Not Responding: com.cfuze.feedlogger EXITING}
10-10 18:20:08.160  1518  3212 D InputManager-JNI: setSystemUiVisibility dexmode: false changed: true displayid: 0 visibility: 0x8018 DD: 0x8018 OD: 0x0
10-10 18:20:08.160  1518  1567 E ViewRootImpl: sendUserActionEvent() returned.
10-10 18:20:08.163  1518  1569 W libprocessgroup: kill(-28808, 9) failed: No such process
10-10 18:20:08.174  1518  1569 I chatty  : uid=1000(system) ActivityManager identical 2 lines
10-10 18:20:08.180  1518  1569 W libprocessgroup: kill(-28808, 9) failed: No such process
10-10 18:20:08.186 29755 29788 W PkgUtils: p: com.google.android.gms, u:150
10-10 18:20:08.187  1518  1569 W libprocessgroup: kill(-28808, 9) failed: No such process
10-10 18:20:08.187  1518  2008 W InputDispatcher: channel 'aaf8fad com.cfuze.feedlogger/com.cfuze.feedlogger.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=683
10-10 18:20:08.187  1518  2008 E InputDispatcher: channel 'aaf8fad com.cfuze.feedlogger/com.cfuze.feedlogger.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-10 18:20:08.188  1056  6031 E OMXNodeInstance: !!! Observer died. Quickly, do something, ... anything...
10-10 18:20:08.192  1518  1569 W libprocessgroup: kill(-28808, 9) failed: No such process
10-10 18:20:08.197 28918 28993 E chromium: [ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
10-10 18:20:08.197   982   982 I Zygote  : Process 28808 exited due to signal (9)
10-10 18:20:08.197  1518  1569 W libprocessgroup: kill(-28808, 9) failed: No such process
10-10 18:20:08.198  1518  1569 I libprocessgroup: Successfully killed process cgroup uid 10452 pid 28808 in 64ms
10-10 18:20:08.198  1518  5143 D MediaFocusControl: AudioFocus audio focus client died
10-10 18:20:08.198  1518  5143 I MediaFocusControl: AudioFocus  removeFocusStackEntryOnDeath(): removing entry for android.os.BinderProxy@f621e6
10-10 18:20:08.199  1011  1011 I ResourceManagerService: MediaInfo removed 921600 (width 1280 height 720) remained 17694720 
10-10 18:20:08.199  1015  1015 I RemoteDisplayService: client is died. remove listener for key (55)
10-10 18:20:08.199  1011  1011 I ResourceManagerService: getMediaResourceInfo resourceType : 2, size : 0
10-10 18:20:08.200 28918 29644 E chromium: [ERROR:render_media_log.cc(27)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decode error"}
10-10 18:20:08.200  1518  5143 I WindowManager: WIN DEATH: Window{aaf8fad u0 com.cfuze.feedlogger/com.cfuze.feedlogger.MainActivity}
10-10 18:20:08.200  3688  3853 V ResourceManagerHelper-JNI: JNIMediaResourceHelper::notify eventType : 2, ext1 : 0, ext2 : 0
10-10 18:20:08.200  3688  3853 V ResourceManagerHelper-JNI: notify eventType : 2, ext1 : 0, ext2 : 0
10-10 18:20:08.200  3688  3688 I SemMediaResourceHelper: onRemove
10-10 18:20:08.200 25642 25654 V ResourceManagerHelper-JNI: JNIMediaResourceHelper::notify eventType : 2, ext1 : 0, ext2 : 0
10-10 18:20:08.200  4981  5204 I SAFrameworkService: Package [com.cfuze.feedlogger] has died!!
```

There was not much else in the log and nothing in the console.  I have log statements every line and everything seemed to be good.   It shows message sent successfully and message received

**Comment by guy-keller** [comment]
@munsterlander 

Would you be able to provide the JS logs too?
https://ionic.zone/debug/remote-debug-your-app#android

Some debugging tips: 
* Add lots of console.log / every method, line, callback. ( PS: you seem to be doing that already )
* Surround the whole method in a big try/catch block.

```
function goGalaxy(val){
  try {
    // put your code that does things here
  } catch (e) {
    console.log('ERROR! Something real bad happened, msg: ' + JSON.stringify(e));
  }
}
```

The logcat logs are not particularly helpful this time around. Thanks!

**Comment by munsterlander** [comment]
Will do. What's interesting, is it looks like the watch app crashes and then the phone app crashes. As soon as I get back, I will run those logs.

**Comment by guy-keller** [comment]
Hi @munsterlander ,

In addition to the above, try using this 'findPeerSuccess' callback instead:

```
var findPeerSuccess = function(cdvMsg) {
  console.log("Peer found success, msg: "+cdvMsg);
  // Waits for 1.5secs, SAP 'should have' found all peers after that..
  window.setTimeout( () => {
    // Sends a message to the Watch
    SamsungAccessoryPlugin.sendMessage(sendMessageSuccess, sendMessageFailure, msg);    
  }, 1500);
};
```

As you can see the 'SAP' protocol can be a bit tricky to deal with.
Please let me know how you go, cheers!

**Comment by guy-keller** [comment]
Hello @munsterlander ,

Did you manage to get it all going?

Cheers!

**Comment by guy-keller** [comment]
Closing this issue as things must be working now :)

**Comment by munsterlander** [comment]
Sorry, the js logs didn't show anything and they both are crashing but it's not due to the plugin code. We are chasing the error currently and if we figure it out, I will let you know.
